#!/bin/bash

# check whether repository is clean
if [[ -n "$(git status -s)" ]]
then
  echo "you need to commit pending changes first"
  exit 1
fi

# get parameters
if [[ "$#" -eq 0 ]]
then
  echo "you need to specify the version (#.#.#)"
  exit 1
fi
VERSION="$1"
DATE="$(date -I)"

# update toolbox description with version and date
echo "updating toolbox description"
sed -i 's/^% Version .*/% Version '$VERSION' '$DATE'/' toolbox/Contents.m

# create release file
echo "zipping toolbox as release asset"
RFN="cvcrossmanova-$VERSION"
ln -s toolbox/ "$RFN"
zip "$RFN.zip" "$RFN"/*
rm "$RFN"

exit 2

# commit changed toolbox description with release version & push 
echo "creating commit for release"
git commit -a -m "Release version $VERSION"
git push

# create & push tag
echo "creating tag for release"
TAG="v$VERSION"
git tag "$VERSION"
git push --tags

# create release
echo "creating release with tag $TAG and asset $RFN.zip"
gh release create "$TAG" "$RFN.zip"

echo "you can now delete $RFN.zip"
