project:
  type: website
  output-dir: ../docs/

date: last-modified
date-format: YYYY–M–D
published-title: last modified

website:
  title: "CvCrossManova Toolbox"
  sidebar:
    title: "CvCrossManova Toolbox"
    search: true
    contents: auto

format:
  html:
    from: markdown
    theme: cosmo
    highlight-style: tango
    css: styles.css
    toc: true
    toc-expand: true
    toc-title: "{{< meta title >}}"
    code-overflow: wrap
    grid:
    #   sidebar-width: 310px
      margin-width: 300px
