project:
  type: website
  output-dir: ../docs/

website:
  title: "CvCrossManova"
  sidebar:
    title: "CvCrossManova"
    search: true
    contents: auto
    collapse-level: 1

format:
  html:
    from: markdown
    theme: cosmo
    toc: true
    code-overflow: wrap
    highlight-style: tango
    header-includes: |
      <style>
        code:not(.sourceCode),
        p code:not(.sourceCode),
        li code:not(.sourceCode),
        td code:not(.sourceCode) {
          background-color: transparent;
          color: inherit;
          padding: revert;
        }
      </style>


    grid:
      sidebar-width: 350px
      margin-width: 350px
