project:
  type: website
  output-dir: ../docs/

website:
  title: "CvCrossManova"
  sidebar:
    title: "CvCrossManova"
    search: true
    contents: auto
    collapse-level: 1

format:
  html:
    from: markdown
    theme: cosmo
    toc: true
    code-overflow: wrap
    grid:
      sidebar-width: 350px
      margin-width: 350px
